### ISSUE TITLE
How long does it take to convert 10,000 ids?

### ISSUE THREAD

**Issue by amk11** [bacitracin/Twitter-UserIDs_to_Usernames#1]
How long does it take to convert 10,000 ids?

**Comment by bacitracin** [comment]
So, I haven't touched this script in a year or so, but looking back at it, it's currently incredibly inefficient as it does individual user lookups (good enough for what I needed at the time).

To fix this, you could tweak it to pass an array of comma separated UserIDs instead, as suggested here https://dev.twitter.com/rest/reference/get/users/lookup

They'll return up to 100 users per request, so for your 10k ids, it would be 100 requests. They allow you 60 requests/15 min, so that's not too terrible. I would guess that it would take a couple of hours worst case scenario.

**Comment by ghost** [comment]
How would you do that? I'm a complete noob when it comes to python.

**Comment by bacitracin** [comment]
Well, you'd make a comma separated list of all your user_ids first and save it to a variable.

And then instead of passing in each individual id and evaluating it for username
twitter.lookup_user(user_id)

you'd give it a list instead
twitter.lookup_user(array_of_100_user_ids)

and then access that object to grab your username data. 

Also just noticed, it looks like they suggest using POST instead of GET for these large requests.

**Comment by bacitracin** [comment]
I'll definitely update this script to handle large loads when I have time, but for now I'm closing this issue.
